<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Seeder;

class AdminSeeder extends Seeder
{
    public function run()
    {
        $healthcareWorkers = [
            // DOKTER SPESIALIS DIABETES
            [
                'nama_lengkap' => 'Dr. Ahmad Fauzi SpPD KEMD FINASIM',
                'email' => 'ardhikayanuar58@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '085933648537',
            ],
            [
                'nama_lengkap' => 'Dr. Siti Rahayu SpPD KEMD MKes',
                'email' => 'drsitirahayu42@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081355577799',
            ],
            [
                'nama_lengkap' => 'Dr. Budi Santoso SpPD KEMD FINASIM',
                'email' => 'drbudisantoso67@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081244466688',
            ],
            [
                'nama_lengkap' => 'Dr. Maya Sari SpPD KEMD MSc',
                'email' => 'drmayasari53@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081388899900',
            ],
            [
                'nama_lengkap' => 'Dr. Rizky Maulana SpPD KEMD PhD',
                'email' => 'drrizkymaulana38@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081233344455',
            ],
            [
                'nama_lengkap' => 'Dr. Dian Permatasari SpPD KEMD',
                'email' => 'drdianpermatasari71@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081277788833',
            ],
            [
                'nama_lengkap' => 'Dr. Hendra Gunawan SpPD KEMD FINASIM',
                'email' => 'drhendragunawan49@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081299900011',
            ],
            [
                'nama_lengkap' => 'Dr. Fitriani SpPD KEMD MKes',
                'email' => 'drfitriani76@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081311122244',
            ],
            [
                'nama_lengkap' => 'Dr. Agus Setiawan SpPD KEMD',
                'email' => 'dragussetiawan64@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081277788899',
            ],
            [
                'nama_lengkap' => 'Dr. Rina Wijaya SpPD KEMD MSc',
                'email' => 'drrinawijaya45@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081366699922',
            ],
            [
                'nama_lengkap' => 'Dr. Andi Pratama SpPD KEMD FINASIM',
                'email' => 'drandipratama82@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081211122233',
            ],
            [
                'nama_lengkap' => 'Dr. Sari Indah SpPD KEMD MKes',
                'email' => 'drsariindah59@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081322233355',
            ],
            [
                'nama_lengkap' => 'Dr. Eko Nugroho SpPD KEMD PhD',
                'email' => 'drekonugroho73@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081333344466',
            ],
            [
                'nama_lengkap' => 'Dr. Lestari SpPD KEMD FINASIM',
                'email' => 'drlestari51@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081344455577',
            ],
            [
                'nama_lengkap' => 'Dr. Bambang Sutrisno SpPD KEMD',
                'email' => 'drbambangsutrisno68@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081355566688',
            ],
            [
                'nama_lengkap' => 'Dr. Citra Dewi SpPD KEMD MKes',
                'email' => 'drcitradewi47@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081366677799',
            ],
            [
                'nama_lengkap' => 'Dr. Joko Prasetyo SpPD KEMD FINASIM',
                'email' => 'drjokoprasetyo79@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081377788800',
            ],
            [
                'nama_lengkap' => 'Dr. Ani Lestari SpPD KEMD MSc',
                'email' => 'dranilestari62@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081388899911',
            ],
            [
                'nama_lengkap' => 'Dr. Rudi Hermawan SpPD KEMD PhD',
                'email' => 'drrudihermawan55@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081399900022',
            ],
            [
                'nama_lengkap' => 'Dr. Dewi Anggraeni SpPD KEMD FINASIM',
                'email' => 'drdewianggraeni41@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081300011133',
            ],
            [
                'nama_lengkap' => 'Dr. Fajar Siddiq SpPD KEMD',
                'email' => 'drfajarsiddiq74@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081311122344',
            ],
            [
                'nama_lengkap' => 'Dr. Gita Maharani SpPD KEMD MKes',
                'email' => 'drgitamaharani56@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081322233455',
            ],
            [
                'nama_lengkap' => 'Dr. Heru Prasetyo SpPD KEMD FINASIM',
                'email' => 'drheruprasetyo83@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081333344566',
            ],
            [
                'nama_lengkap' => 'Dr. Intan Permata SpPD KEMD MSc',
                'email' => 'drintanpermata48@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081344455677',
            ],
            [
                'nama_lengkap' => 'Dr. Jefri Alexander SpPD KEMD PhD',
                'email' => 'drjefrialexander72@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081355566788',
            ],
            [
                'nama_lengkap' => 'Dr. Kartika Sari SpPD KEMD FINASIM',
                'email' => 'drkartikasari61@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081366677899',
            ],
            [
                'nama_lengkap' => 'Dr. Leo Fernando SpPD KEMD',
                'email' => 'drleofernando77@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081377788900',
            ],
            [
                'nama_lengkap' => 'Dr. Mila Anggraini SpPD KEMD MKes',
                'email' => 'drmilaanggraini54@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081388899011',
            ],
            [
                'nama_lengkap' => 'Dr. Nanda Putra SpPD KEMD FINASIM',
                'email' => 'drnandaputra69@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081399900122',
            ],
            [
                'nama_lengkap' => 'Dr. Olivia Sanjaya SpPD KEMD MSc',
                'email' => 'droliviasanjaya46@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Dokter',
                'nomor_telepon' => '081300011233',
            ],

            // PERAWAT SPESIALIS DIABETES
            [
                'nama_lengkap' => 'Maria SKep Ners MNurs',
                'email' => 'nursemaria63@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081298765432',
            ],
            [
                'nama_lengkap' => 'Dewi Anggraeni SKep Ners',
                'email' => 'nursedewianggraeni52@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081311122233',
            ],
            [
                'nama_lengkap' => 'Rudi Hermawan SKep Ners MNurs',
                'email' => 'nurserudihermawan75@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081322233344',
            ],
            [
                'nama_lengkap' => 'Sari Indah SKep Ners',
                'email' => 'nursesariindah58@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081333344455',
            ],
            [
                'nama_lengkap' => 'Joko Prasetyo SKep Ners MNurs',
                'email' => 'nursejokoprasetyo81@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081344455566',
            ],
            [
                'nama_lengkap' => 'Ani Lestari SKep Ners',
                'email' => 'nurseanilestari44@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081355566677',
            ],
            [
                'nama_lengkap' => 'Bambang Sutrisno SKep Ners MNurs',
                'email' => 'nursebambangsutrisno78@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081366677788',
            ],
            [
                'nama_lengkap' => 'Citra Dewi SKep Ners',
                'email' => 'nursecitradewi65@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081377788899',
            ],
            [
                'nama_lengkap' => 'Eko Nugroho SKep Ners MNurs',
                'email' => 'nurseekonugroho57@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081388899900',
            ],
            [
                'nama_lengkap' => 'Fitri Handayani SKep Ners',
                'email' => 'nursefitrihandayani43@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081399900011',
            ],
            [
                'nama_lengkap' => 'Adi Susanto SKep Ners MNurs',
                'email' => 'nurseadisusanto66@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081310011122',
            ],
            [
                'nama_lengkap' => 'Maya Sari SKep Ners',
                'email' => 'nursemayasari39@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081321122233',
            ],
            [
                'nama_lengkap' => 'Rizky Maulana SKep Ners MNurs',
                'email' => 'nurserizkymaulana84@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081332233344',
            ],
            [
                'nama_lengkap' => 'Diana Putri SKep Ners',
                'email' => 'nursedianaputri70@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081343344455',
            ],
            [
                'nama_lengkap' => 'Hendra Gunawan SKep Ners MNurs',
                'email' => 'nursehendragunawan50@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081354455566',
            ],
            [
                'nama_lengkap' => 'Lina Marlina SKep Ners',
                'email' => 'nurselinamarlina85@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081365566677',
            ],
            [
                'nama_lengkap' => 'Fajar Siddiq SKep Ners MNurs',
                'email' => 'nursefajarsiddiq60@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081376677788',
            ],
            [
                'nama_lengkap' => 'Ratna Komala SKep Ners',
                'email' => 'nurseratnakomala86@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081387788899',
            ],
            [
                'nama_lengkap' => 'Irfan Maulana SKep Ners MNurs',
                'email' => 'nurseirfanmaulana40@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Laki-laki',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081398899900',
            ],
            [
                'nama_lengkap' => 'Siska Andini SKep Ners',
                'email' => 'nursesiskaandini87@gmail.com',
                'password' => bcrypt('password'),
                'jenis_kelamin' => 'Perempuan',
                'hak_akses' => 'Perawat',
                'nomor_telepon' => '081309900011',
            ]
        ];

        foreach ($healthcareWorkers as $worker) {
            Admin::create($worker);
        }
    }
}