<?php

namespace Database\Seeders;

use App\Models\DataKesehatan;
use App\Models\Pengguna;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DataKesehatanSeeder extends Seeder
{
    public function run()
    {
        $dataKesehatanList = [
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 170,
                'berat_badan' => 65,
                'gula_darah' => 98,
                'lingkar_pinggang' => 82,
                'tensi_darah' => 120,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 160,
                'berat_badan' => 55,
                'gula_darah' => 110,
                'lingkar_pinggang' => 78,
                'tensi_darah' => 115,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 172,
                'berat_badan' => 70,
                'gula_darah' => 102,
                'lingkar_pinggang' => 85,
                'tensi_darah' => 122,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 158,
                'berat_badan' => 50,
                'gula_darah' => 95,
                'lingkar_pinggang' => 74,
                'tensi_darah' => 110,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 175,
                'berat_badan' => 72,
                'gula_darah' => 105,
                'lingkar_pinggang' => 88,
                'tensi_darah' => 125,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 162,
                'berat_badan' => 57,
                'gula_darah' => 108,
                'lingkar_pinggang' => 76,
                'tensi_darah' => 118,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 178,
                'berat_badan' => 80,
                'gula_darah' => 112,
                'lingkar_pinggang' => 90,
                'tensi_darah' => 128,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 159,
                'berat_badan' => 52,
                'gula_darah' => 99,
                'lingkar_pinggang' => 75,
                'tensi_darah' => 112,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 173,
                'berat_badan' => 78,
                'gula_darah' => 115,
                'lingkar_pinggang' => 89,
                'tensi_darah' => 130,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 161,
                'berat_badan' => 54,
                'gula_darah' => 92,
                'lingkar_pinggang' => 73,
                'tensi_darah' => 108,
            ],
            // Data tambahan untuk 90 pengguna lainnya
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 168,
                'berat_badan' => 68,
                'gula_darah' => 100,
                'lingkar_pinggang' => 84,
                'tensi_darah' => 122,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 165,
                'berat_badan' => 62,
                'gula_darah' => 112,
                'lingkar_pinggang' => 80,
                'tensi_darah' => 118,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 175,
                'berat_badan' => 74,
                'gula_darah' => 104,
                'lingkar_pinggang' => 86,
                'tensi_darah' => 124,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 163,
                'berat_badan' => 58,
                'gula_darah' => 97,
                'lingkar_pinggang' => 76,
                'tensi_darah' => 112,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 180,
                'berat_badan' => 82,
                'gula_darah' => 108,
                'lingkar_pinggang' => 92,
                'tensi_darah' => 128,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 158,
                'berat_badan' => 56,
                'gula_darah' => 106,
                'lingkar_pinggang' => 78,
                'tensi_darah' => 120,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 182,
                'berat_badan' => 85,
                'gula_darah' => 115,
                'lingkar_pinggang' => 94,
                'tensi_darah' => 132,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 160,
                'berat_badan' => 53,
                'gula_darah' => 101,
                'lingkar_pinggang' => 77,
                'tensi_darah' => 114,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 176,
                'berat_badan' => 80,
                'gula_darah' => 118,
                'lingkar_pinggang' => 91,
                'tensi_darah' => 134,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 162,
                'berat_badan' => 55,
                'gula_darah' => 94,
                'lingkar_pinggang' => 75,
                'tensi_darah' => 110,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 169,
                'berat_badan' => 70,
                'gula_darah' => 103,
                'lingkar_pinggang' => 83,
                'tensi_darah' => 123,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 164,
                'berat_badan' => 63,
                'gula_darah' => 114,
                'lingkar_pinggang' => 81,
                'tensi_darah' => 119,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 174,
                'berat_badan' => 73,
                'gula_darah' => 106,
                'lingkar_pinggang' => 87,
                'tensi_darah' => 126,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 161,
                'berat_badan' => 59,
                'gula_darah' => 99,
                'lingkar_pinggang' => 77,
                'tensi_darah' => 113,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 179,
                'berat_badan' => 83,
                'gula_darah' => 110,
                'lingkar_pinggang' => 93,
                'tensi_darah' => 129,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 159,
                'berat_badan' => 57,
                'gula_darah' => 107,
                'lingkar_pinggang' => 79,
                'tensi_darah' => 121,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 181,
                'berat_badan' => 86,
                'gula_darah' => 116,
                'lingkar_pinggang' => 95,
                'tensi_darah' => 133,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 163,
                'berat_badan' => 54,
                'gula_darah' => 102,
                'lingkar_pinggang' => 78,
                'tensi_darah' => 115,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 177,
                'berat_badan' => 81,
                'gula_darah' => 119,
                'lingkar_pinggang' => 92,
                'tensi_darah' => 135,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 164,
                'berat_badan' => 56,
                'gula_darah' => 96,
                'lingkar_pinggang' => 76,
                'tensi_darah' => 111,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 171,
                'berat_badan' => 71,
                'gula_darah' => 104,
                'lingkar_pinggang' => 84,
                'tensi_darah' => 124,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 166,
                'berat_badan' => 64,
                'gula_darah' => 115,
                'lingkar_pinggang' => 82,
                'tensi_darah' => 120,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 176,
                'berat_badan' => 75,
                'gula_darah' => 107,
                'lingkar_pinggang' => 88,
                'tensi_darah' => 127,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 162,
                'berat_badan' => 60,
                'gula_darah' => 100,
                'lingkar_pinggang' => 78,
                'tensi_darah' => 114,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 180,
                'berat_badan' => 84,
                'gula_darah' => 111,
                'lingkar_pinggang' => 94,
                'tensi_darah' => 130,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 160,
                'berat_badan' => 58,
                'gula_darah' => 108,
                'lingkar_pinggang' => 80,
                'tensi_darah' => 122,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 183,
                'berat_badan' => 87,
                'gula_darah' => 117,
                'lingkar_pinggang' => 96,
                'tensi_darah' => 134,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 165,
                'berat_badan' => 55,
                'gula_darah' => 103,
                'lingkar_pinggang' => 79,
                'tensi_darah' => 116,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 178,
                'berat_badan' => 82,
                'gula_darah' => 120,
                'lingkar_pinggang' => 93,
                'tensi_darah' => 136,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 165,
                'berat_badan' => 57,
                'gula_darah' => 97,
                'lingkar_pinggang' => 77,
                'tensi_darah' => 112,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 172,
                'berat_badan' => 72,
                'gula_darah' => 105,
                'lingkar_pinggang' => 85,
                'tensi_darah' => 125,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 167,
                'berat_badan' => 65,
                'gula_darah' => 116,
                'lingkar_pinggang' => 83,
                'tensi_darah' => 121,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 177,
                'berat_badan' => 76,
                'gula_darah' => 108,
                'lingkar_pinggang' => 89,
                'tensi_darah' => 128,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 163,
                'berat_badan' => 61,
                'gula_darah' => 101,
                'lingkar_pinggang' => 79,
                'tensi_darah' => 115,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 181,
                'berat_badan' => 85,
                'gula_darah' => 112,
                'lingkar_pinggang' => 95,
                'tensi_darah' => 131,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 161,
                'berat_badan' => 59,
                'gula_darah' => 109,
                'lingkar_pinggang' => 81,
                'tensi_darah' => 123,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 184,
                'berat_badan' => 88,
                'gula_darah' => 118,
                'lingkar_pinggang' => 97,
                'tensi_darah' => 135,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 166,
                'berat_badan' => 56,
                'gula_darah' => 104,
                'lingkar_pinggang' => 80,
                'tensi_darah' => 117,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 179,
                'berat_badan' => 83,
                'gula_darah' => 121,
                'lingkar_pinggang' => 94,
                'tensi_darah' => 137,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 166,
                'berat_badan' => 58,
                'gula_darah' => 98,
                'lingkar_pinggang' => 78,
                'tensi_darah' => 113,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 173,
                'berat_badan' => 73,
                'gula_darah' => 106,
                'lingkar_pinggang' => 86,
                'tensi_darah' => 126,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 168,
                'berat_badan' => 66,
                'gula_darah' => 117,
                'lingkar_pinggang' => 84,
                'tensi_darah' => 122,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 178,
                'berat_badan' => 77,
                'gula_darah' => 109,
                'lingkar_pinggang' => 90,
                'tensi_darah' => 129,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 164,
                'berat_badan' => 62,
                'gula_darah' => 102,
                'lingkar_pinggang' => 80,
                'tensi_darah' => 116,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 182,
                'berat_badan' => 86,
                'gula_darah' => 113,
                'lingkar_pinggang' => 96,
                'tensi_darah' => 132,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 162,
                'berat_badan' => 60,
                'gula_darah' => 110,
                'lingkar_pinggang' => 82,
                'tensi_darah' => 124,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 185,
                'berat_badan' => 89,
                'gula_darah' => 119,
                'lingkar_pinggang' => 98,
                'tensi_darah' => 136,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 167,
                'berat_badan' => 57,
                'gula_darah' => 105,
                'lingkar_pinggang' => 81,
                'tensi_darah' => 118,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 180,
                'berat_badan' => 84,
                'gula_darah' => 122,
                'lingkar_pinggang' => 95,
                'tensi_darah' => 138,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 167,
                'berat_badan' => 59,
                'gula_darah' => 99,
                'lingkar_pinggang' => 79,
                'tensi_darah' => 114,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 174,
                'berat_badan' => 74,
                'gula_darah' => 107,
                'lingkar_pinggang' => 87,
                'tensi_darah' => 127,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 169,
                'berat_badan' => 67,
                'gula_darah' => 118,
                'lingkar_pinggang' => 85,
                'tensi_darah' => 123,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 179,
                'berat_badan' => 78,
                'gula_darah' => 110,
                'lingkar_pinggang' => 91,
                'tensi_darah' => 130,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 165,
                'berat_badan' => 63,
                'gula_darah' => 103,
                'lingkar_pinggang' => 81,
                'tensi_darah' => 117,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 183,
                'berat_badan' => 87,
                'gula_darah' => 114,
                'lingkar_pinggang' => 97,
                'tensi_darah' => 133,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 163,
                'berat_badan' => 61,
                'gula_darah' => 111,
                'lingkar_pinggang' => 83,
                'tensi_darah' => 125,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 186,
                'berat_badan' => 90,
                'gula_darah' => 120,
                'lingkar_pinggang' => 99,
                'tensi_darah' => 137,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 168,
                'berat_badan' => 58,
                'gula_darah' => 106,
                'lingkar_pinggang' => 82,
                'tensi_darah' => 119,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 181,
                'berat_badan' => 85,
                'gula_darah' => 123,
                'lingkar_pinggang' => 96,
                'tensi_darah' => 139,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 168,
                'berat_badan' => 60,
                'gula_darah' => 100,
                'lingkar_pinggang' => 80,
                'tensi_darah' => 115,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 175,
                'berat_badan' => 75,
                'gula_darah' => 108,
                'lingkar_pinggang' => 88,
                'tensi_darah' => 128,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 170,
                'berat_badan' => 68,
                'gula_darah' => 119,
                'lingkar_pinggang' => 86,
                'tensi_darah' => 124,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 180,
                'berat_badan' => 79,
                'gula_darah' => 111,
                'lingkar_pinggang' => 92,
                'tensi_darah' => 131,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 166,
                'berat_badan' => 64,
                'gula_darah' => 104,
                'lingkar_pinggang' => 82,
                'tensi_darah' => 118,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 184,
                'berat_badan' => 88,
                'gula_darah' => 115,
                'lingkar_pinggang' => 98,
                'tensi_darah' => 134,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 164,
                'berat_badan' => 62,
                'gula_darah' => 112,
                'lingkar_pinggang' => 84,
                'tensi_darah' => 126,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 187,
                'berat_badan' => 91,
                'gula_darah' => 121,
                'lingkar_pinggang' => 100,
                'tensi_darah' => 138,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 169,
                'berat_badan' => 59,
                'gula_darah' => 107,
                'lingkar_pinggang' => 83,
                'tensi_darah' => 120,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Tidak',
                'tinggi_badan' => 182,
                'berat_badan' => 86,
                'gula_darah' => 124,
                'lingkar_pinggang' => 97,
                'tensi_darah' => 140,
            ],
            [
                'riwayat_keluarga_diabetes' => 'Ya',
                'tinggi_badan' => 169,
                'berat_badan' => 61,
                'gula_darah' => 101,
                'lingkar_pinggang' => 81,
                'tensi_darah' => 116,
            ],
        ];

        $penggunaList = Pengguna::all();

        foreach ($penggunaList as $index => $pengguna) {
            $dataIndex = $index % count($dataKesehatanList);
            
            // Hitung umur dari tanggal lahir pengguna
            $tanggalLahir = Carbon::parse($pengguna->tanggal_lahir);
            $umur = $tanggalLahir->diffInYears(Carbon::now());
            
            DataKesehatan::create([
                'nik' => $pengguna->nik,
                'tanggal_pemeriksaan' => now()->subDays(rand(1, 365)),
                'riwayat_keluarga_diabetes' => $dataKesehatanList[$dataIndex]['riwayat_keluarga_diabetes'],
                'umur' => $umur, // Menggunakan umur dari data pengguna
                'tinggi_badan' => $dataKesehatanList[$dataIndex]['tinggi_badan'],
                'berat_badan' => $dataKesehatanList[$dataIndex]['berat_badan'],
                'gula_darah' => $dataKesehatanList[$dataIndex]['gula_darah'],
                'lingkar_pinggang' => $dataKesehatanList[$dataIndex]['lingkar_pinggang'],
                'tensi_darah' => $dataKesehatanList[$dataIndex]['tensi_darah'],
            ]);
        }
    }
}