<?php

namespace Database\Seeders;

use App\Models\Pengguna;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PenggunaSeeder extends Seeder
{
    public function run()
    {
        $penggunaData = [
            [
                'nik' => '3501010101010001',
                'email' => 'budi.santoso@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Budi Santoso',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-15',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Merdeka No.10, Jakarta Pusat',
                'nomor_telepon' => '081234567801',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3501010101010002',
                'email' => 'siti.rahma@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Siti Rahmawati',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1992-03-20',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Asia Afrika No.22, Bandung',
                'nomor_telepon' => '081234567802',
                'nama_ibu_kandung' => 'Nurhayati',
            ],
            [
                'nik' => '3501010101010003',
                'email' => 'agus.prasetyo@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Agus Prasetyo',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1989-07-11',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Diponegoro No.7, Surabaya',
                'nomor_telepon' => '081234567803',
                'nama_ibu_kandung' => 'Sri Wahyuni',
            ],
            [
                'nik' => '3501010101010004',
                'email' => 'dewi.lestari@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dewi Lestari',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1994-12-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Malioboro No.3, Yogyakarta',
                'nomor_telepon' => '081234567804',
                'nama_ibu_kandung' => 'Kartini',
            ],
            [
                'nik' => '3501010101010005',
                'email' => 'andi.firmansyah@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Andi Firmansyah',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1991-06-21',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Pettarani No.12, Makassar',
                'nomor_telepon' => '081234567805',
                'nama_ibu_kandung' => 'Rukmini',
            ],
            [
                'nik' => '3501010101010006',
                'email' => 'lina.anggraini@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lina Anggraini',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1993-04-10',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Pandanaran No.18, Semarang',
                'nomor_telepon' => '081234567806',
                'nama_ibu_kandung' => 'Rohana',
            ],
            [
                'nik' => '3501010101010007',
                'email' => 'rizky.maulana@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rizky Maulana',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1995-08-30',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gatot Subroto No.25, Medan',
                'nomor_telepon' => '081234567807',
                'nama_ibu_kandung' => 'Mardiana',
            ],
            [
                'nik' => '3501010101010008',
                'email' => 'ayu.wulandari@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ayu Wulandari',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '1996-11-18',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Kuta No.9, Denpasar',
                'nomor_telepon' => '081234567808',
                'nama_ibu_kandung' => 'Ni Luh Sari',
            ],
            [
                'nik' => '3501010101010009',
                'email' => 'heri.susanto@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Heri Susanto',
                'tempat_lahir' => 'Balikpapan',
                'tanggal_lahir' => '1988-09-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jendral Sudirman No.8, Balikpapan',
                'nomor_telepon' => '081234567809',
                'nama_ibu_kandung' => 'Sulastri',
            ],
            [
                'nik' => '3501010101010010',
                'email' => 'fitri.handayani@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Fitri Handayani',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1997-05-27',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Ampera No.6, Palembang',
                'nomor_telepon' => '081234567810',
                'nama_ibu_kandung' => 'Yuliani',
            ],
            [
                'nik' => '3501010101010011',
                'email' => 'joko.widodo@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Joko Widodo',
                'tempat_lahir' => 'Surakarta',
                'tanggal_lahir' => '1985-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Slamet Riyadi No.45, Surakarta',
                'nomor_telepon' => '081234567811',
                'nama_ibu_kandung' => 'Sudjiatmi',
            ],
            [
                'nik' => '3501010101010012',
                'email' => 'sri.mulyani@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sri Mulyani',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1982-08-26',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Dago No.78, Bandung',
                'nomor_telepon' => '081234567812',
                'nama_ibu_kandung' => 'Retno Samudro',
            ],
            [
                'nik' => '3501010101010013',
                'email' => 'ahmad.dahlan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ahmad Dahlan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1990-11-03',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Solo No.23, Yogyakarta',
                'nomor_telepon' => '081234567813',
                'nama_ibu_kandung' => 'Siti Walidah',
            ],
            [
                'nik' => '3501010101010014',
                'email' => 'ratna.sari@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ratna Sari',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1993-04-17',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Thamrin No.56, Jakarta Pusat',
                'nomor_telepon' => '081234567814',
                'nama_ibu_kandung' => 'Dewi Kusuma',
            ],
            [
                'nik' => '3501010101010015',
                'email' => 'bambang.pamungkas@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Bambang Pamungkas',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1987-07-10',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gajah Mada No.34, Semarang',
                'nomor_telepon' => '081234567815',
                'nama_ibu_kandung' => 'Siti Maryam',
            ],
            [
                'nik' => '3501010101010016',
                'email' => 'dian.sastrowardoyo@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dian Sastrowardoyo',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1995-03-16',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sudirman No.89, Jakarta Selatan',
                'nomor_telepon' => '081234567816',
                'nama_ibu_kandung' => 'Sri Hastuti',
            ],
            [
                'nik' => '3501010101010017',
                'email' => 'iwan.fals@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Iwan Fals',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-09-03',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cipinang No.12, Jakarta Timur',
                'nomor_telepon' => '081234567817',
                'nama_ibu_kandung' => 'Yati',
            ],
            [
                'nik' => '3501010101010018',
                'email' => 'agnes.monica@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Agnes Monica',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1996-07-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kemang No.67, Jakarta Selatan',
                'nomor_telepon' => '081234567818',
                'nama_ibu_kandung' => 'Jenny Siswono',
            ],
            [
                'nik' => '3501010101010019',
                'email' => 'susi.pudjiastuti@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Susi Pudjiastuti',
                'tempat_lahir' => 'Pangandaran',
                'tanggal_lahir' => '1983-05-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Pantai Barat No.5, Pangandaran',
                'nomor_telepon' => '081234567819',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010020',
                'email' => 'anies.baswedan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Anies Baswedan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1981-05-07',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Mataram No.33, Yogyakarta',
                'nomor_telepon' => '081234567820',
                'nama_ibu_kandung' => 'Aliyah Rasyid',
            ],
            [
                'nik' => '3501010101010021',
                'email' => 'rini.indrawati@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rini Indrawati',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1984-11-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Pemuda No.22, Semarang',
                'nomor_telepon' => '081234567821',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3501010101010022',
                'email' => 'ridwan.kamil@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ridwan Kamil',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1979-10-04',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cihampelas No.45, Bandung',
                'nomor_telepon' => '081234567822',
                'nama_ibu_kandung' => 'Tuti Alawiyah',
            ],
            [
                'nik' => '3501010101010023',
                'email' => 'diana.nurjanah@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Diana Nurjanah',
                'tempat_lahir' => 'Ciamis',
                'tanggal_lahir' => '1992-06-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Merdeka No.11, Ciamis',
                'nomor_telepon' => '081234567823',
                'nama_ibu_kandung' => 'Siti Komariah',
            ],
            [
                'nik' => '3501010101010024',
                'email' => 'tommy.soeharto@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Tommy Soeharto',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1988-07-15',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Menteng No.8, Jakarta Pusat',
                'nomor_telepon' => '081234567824',
                'nama_ibu_kandung' => 'Siti Hartinah',
            ],
            [
                'nik' => '3501010101010025',
                'email' => 'mega.chandrawati@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Mega Chandrawati',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1991-12-19',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Darmo No.77, Surabaya',
                'nomor_telepon' => '081234567825',
                'nama_ibu_kandung' => 'Sukmawati',
            ],
            [
                'nik' => '3501010101010026',
                'email' => 'jokowi.widodo@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Jokowi Widodo',
                'tempat_lahir' => 'Surakarta',
                'tanggal_lahir' => '1986-03-21',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Slamet Riyadi No.56, Surakarta',
                'nomor_telepon' => '081234567826',
                'nama_ibu_kandung' => 'Sudjiatmi',
            ],
            [
                'nik' => '3501010101010027',
                'email' => 'sri.rahayu@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sri Rahayu',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1994-08-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Ijen No.25, Malang',
                'nomor_telepon' => '081234567827',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010028',
                'email' => 'budi.gunawan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Budi Gunawan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1983-02-28',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Malioboro No.44, Yogyakarta',
                'nomor_telepon' => '081234567828',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3501010101010029',
                'email' => 'sari.dewi@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sari Dewi',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1995-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Riau No.32, Bandung',
                'nomor_telepon' => '081234567829',
                'nama_ibu_kandung' => 'Dewi Lestari',
            ],
            [
                'nik' => '3501010101010030',
                'email' => 'agus.harimurti@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Agus Harimurti',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1989-11-10',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gatot Subroto No.67, Jakarta Selatan',
                'nomor_telepon' => '081234567830',
                'nama_ibu_kandung' => 'Siti Nurhaliza',
            ],
            [
                'nik' => '3501010101010031',
                'email' => 'intan.juwita@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Intan Juwita',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1993-01-25',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sisingamangaraja No.15, Medan',
                'nomor_telepon' => '081234567831',
                'nama_ibu_kandung' => 'Rosmalia',
            ],
            [
                'nik' => '3501010101010032',
                'email' => 'doni.anton@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Doni Anton',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1987-04-18',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jendral Sudirman No.34, Palembang',
                'nomor_telepon' => '081234567832',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010033',
                'email' => 'lina.marlina@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lina Marlina',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1996-09-12',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Suryakencana No.22, Bogor',
                'nomor_telepon' => '081234567833',
                'nama_ibu_kandung' => 'Marlina',
            ],
            [
                'nik' => '3501010101010034',
                'email' => 'reza.rahadian@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Reza Rahadian',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-03-05',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cipaganti No.56, Bandung',
                'nomor_telepon' => '081234567834',
                'nama_ibu_kandung' => 'Dewi Rahayu',
            ],
            [
                'nik' => '3501010101010035',
                'email' => 'nina.tamam@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nina Tamam',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1994-07-28',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kebon Sirih No.19, Jakarta Pusat',
                'nomor_telepon' => '081234567835',
                'nama_ibu_kandung' => 'Siti Fatimah',
            ],
            [
                'nik' => '3501010101010036',
                'email' => 'arifin.ilham@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Arifin Ilham',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1982-12-10',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Imam Bonjol No.41, Medan',
                'nomor_telepon' => '081234567836',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010037',
                'email' => 'della.anggraini@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Della Anggraini',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1997-02-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Kupang No.88, Surabaya',
                'nomor_telepon' => '081234567837',
                'nama_ibu_kandung' => 'Rina Anggraini',
            ],
            [
                'nik' => '3501010101010038',
                'email' => 'firman.adi@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Firman Adi',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1985-06-30',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Pandanaran No.29, Semarang',
                'nomor_telepon' => '081234567838',
                'nama_ibu_kandung' => 'Siti Rohana',
            ],
            [
                'nik' => '3501010101010039',
                'email' => 'gita.gutawa@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Gita Gutawa',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1998-08-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kemang Raya No.73, Jakarta Selatan',
                'nomor_telepon' => '081234567839',
                'nama_ibu_kandung' => 'Siti Nurjanah',
            ],
            [
                'nik' => '3501010101010040',
                'email' => 'hadi.prayitno@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Hadi Prayitno',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1984-04-22',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Solo No.18, Yogyakarta',
                'nomor_telepon' => '081234567840',
                'nama_ibu_kandung' => 'Siti Komariah',
            ],
            [
                'nik' => '3501010101010041',
                'email' => 'indah.kusuma@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Indah Kusuma',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1992-10-07',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Cihampelas No.62, Bandung',
                'nomor_telepon' => '081234567841',
                'nama_ibu_kandung' => 'Dewi Kusuma',
            ],
            [
                'nik' => '3501010101010042',
                'email' => 'jaja.mihardja@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Jaja Mihardja',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1981-07-19',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kebon Kacang No.27, Jakarta Pusat',
                'nomor_telepon' => '081234567842',
                'nama_ibu_kandung' => 'Siti Maryam',
            ],
            [
                'nik' => '3501010101010043',
                'email' => 'kartika.sari@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Kartika Sari',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1995-03-03',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Gubeng No.51, Surabaya',
                'nomor_telepon' => '081234567843',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3501010101010044',
                'email' => 'lukman.hakim@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lukman Hakim',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1986-11-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Sisingamangaraja No.38, Medan',
                'nomor_telepon' => '081234567844',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3501010101010045',
                'email' => 'maya.septiani@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Maya Septiani',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1993-05-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Suryakencana No.45, Bogor',
                'nomor_telepon' => '081234567845',
                'nama_ibu_kandung' => 'Septi Wulandari',
            ],
            [
                'nik' => '3501010101010046',
                'email' => 'nurdin.halid@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nurdin Halid',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1980-09-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Sultan Hasanuddin No.23, Makassar',
                'nomor_telepon' => '081234567846',
                'nama_ibu_kandung' => 'Siti Komariah',
            ],
            [
                'nik' => '3501010101010047',
                'email' => 'okta.viani@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Okta Viani',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1996-12-22',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Melawai No.9, Jakarta Selatan',
                'nomor_telepon' => '081234567847',
                'nama_ibu_kandung' => 'Viani Sari',
            ],
            [
                'nik' => '3501010101010048',
                'email' => 'pratama.putra@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Pratama Putra',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-02-17',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Malioboro No.31, Yogyakarta',
                'nomor_telepon' => '081234567848',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010049',
                'email' => 'queena.miranda@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Queena Miranda',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1994-06-09',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Dago No.84, Bandung',
                'nomor_telepon' => '081234567849',
                'nama_ibu_kandung' => 'Miranda Sari',
            ],
            [
                'nik' => '3501010101010050',
                'email' => 'rizal.ramli@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rizal Ramli',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1983-01-30',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gatot Subroto No.92, Jakarta Selatan',
                'nomor_telepon' => '081234567850',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010051',
                'email' => 'salsa.bila@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Salsa Bila',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1997-04-13',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Diponegoro No.16, Medan',
                'nomor_telepon' => '081234567851',
                'nama_ibu_kandung' => 'Bila Sari',
            ],
            [
                'nik' => '3501010101010052',
                'email' => 'taufik.hidayat@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Taufik Hidayat',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1989-08-25',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cipaganti No.71, Bandung',
                'nomor_telepon' => '081234567852',
                'nama_ibu_kandung' => 'Siti Nurhayati',
            ],
            [
                'nik' => '3501010101010053',
                'email' => 'umi.purnama@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Umi Purnama',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1991-11-07',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Darmo No.63, Surabaya',
                'nomor_telepon' => '081234567853',
                'nama_ibu_kandung' => 'Purnama Sari',
            ],
            [
                'nik' => '3501010101010054',
                'email' => 'vino.bastian@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Vino Bastian',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-02-18',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kebon Sirih No.28, Jakarta Pusat',
                'nomor_telepon' => '081234567854',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010055',
                'email' => 'wulan.guritno@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Wulan Guritno',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1995-07-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Solo No.39, Yogyakarta',
                'nomor_telepon' => '081234567855',
                'nama_ibu_kandung' => 'Guritno Sari',
            ],
            [
                'nik' => '3501010101010056',
                'email' => 'xavier.heru@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Xavier Heru',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1987-10-31',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Pandanaran No.52, Semarang',
                'nomor_telepon' => '081234567856',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010057',
                'email' => 'yuni.sari@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Yuni Sari',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1993-03-12',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Riau No.47, Bandung',
                'nomor_telepon' => '081234567857',
                'nama_ibu_kandung' => 'Sari Indah',
            ],
            [
                'nik' => '3501010101010058',
                'email' => 'zainudin.amin@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Zainudin Amin',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-12-05',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Thamrin No.74, Jakarta Pusat',
                'nomor_telepon' => '081234567858',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3501010101010059',
                'email' => 'aini.nurjanah@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Aini Nurjanah',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1996-05-19',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Gubeng No.29, Surabaya',
                'nomor_telepon' => '081234567859',
                'nama_ibu_kandung' => 'Nurjanah Sari',
            ],
            [
                'nik' => '3501010101010060',
                'email' => 'bambang.susilo@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Bambang Susilo',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1982-09-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Mataram No.57, Yogyakarta',
                'nomor_telepon' => '081234567860',
                'nama_ibu_kandung' => 'Susilo Wati',
            ],
            [
                'nik' => '3501010101010061',
                'email' => 'cindy.gracia@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Cindy Gracia',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1994-01-27',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kemang Raya No.38, Jakarta Selatan',
                'nomor_telepon' => '081234567861',
                'nama_ibu_kandung' => 'Gracia Sari',
            ],
            [
                'nik' => '3501010101010062',
                'email' => 'dodi.mizwar@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dodi Mizwar',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1986-04-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cihampelas No.83, Bandung',
                'nomor_telepon' => '081234567862',
                'nama_ibu_kandung' => 'Siti Maryam',
            ],
            [
                'nik' => '3501010101010063',
                'email' => 'eka.gustiwana@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Eka Gustiwana',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1990-07-21',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Sisingamangaraja No.54, Medan',
                'nomor_telepon' => '081234567863',
                'nama_ibu_kandung' => 'Gustiwana Sari',
            ],
            [
                'nik' => '3501010101010064',
                'email' => 'fira.titania@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Fira Titania',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1997-10-03',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Kupang No.72, Surabaya',
                'nomor_telepon' => '081234567864',
                'nama_ibu_kandung' => 'Titania Sari',
            ],
            [
                'nik' => '3501010101010065',
                'email' => 'gilang.ramadhan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Gilang Ramadhan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1988-12-16',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kebon Kacang No.41, Jakarta Pusat',
                'nomor_telepon' => '081234567865',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010066',
                'email' => 'hanny.saputri@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Hanny Saputri',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1992-02-28',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Dago No.96, Bandung',
                'nomor_telepon' => '081234567866',
                'nama_ibu_kandung' => 'Saputri Wati',
            ],
            [
                'nik' => '3501010101010067',
                'email' => 'irsyad.ilham@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Irsyad Ilham',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1985-05-11',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Malioboro No.68, Yogyakarta',
                'nomor_telepon' => '081234567867',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010068',
                'email' => 'jessica.mila@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Jessica Mila',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1995-08-24',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Melawai No.17, Jakarta Selatan',
                'nomor_telepon' => '081234567868',
                'nama_ibu_kandung' => 'Mila Sari',
            ],
            [
                'nik' => '3501010101010069',
                'email' => 'kurniawan.dewa@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Kurniawan Dewa',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1983-11-06',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gajah Mada No.61, Semarang',
                'nomor_telepon' => '081234567869',
                'nama_ibu_kandung' => 'Siti Nurhayati',
            ],
            [
                'nik' => '3501010101010070',
                'email' => 'laila.choiriah@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Laila Choiriah',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1991-01-19',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Diponegoro No.84, Surabaya',
                'nomor_telepon' => '081234567870',
                'nama_ibu_kandung' => 'Choiriah Sari',
            ],
            [
                'nik' => '3501010101010071',
                'email' => 'muhammad.ali@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Muhammad Ali',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1987-04-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gatot Subroto No.105, Jakarta Selatan',
                'nomor_telepon' => '081234567871',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3501010101010072',
                'email' => 'nadia.putri@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nadia Putri',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1996-06-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Cipaganti No.112, Bandung',
                'nomor_telepon' => '081234567872',
                'nama_ibu_kandung' => 'Putri Sari',
            ],
            [
                'nik' => '3501010101010073',
                'email' => 'oscar.lawalata@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Oscar Lawalata',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1989-09-28',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Imam Bonjol No.76, Medan',
                'nomor_telepon' => '081234567873',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3501010101010074',
                'email' => 'putri.tanjung@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Putri Tanjung',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1993-12-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kebon Sirih No.53, Jakarta Pusat',
                'nomor_telepon' => '081234567874',
                'nama_ibu_kandung' => 'Tanjung Sari',
            ],
            [
                'nik' => '3501010101010075',
                'email' => 'qory.sandioriva@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Qory Sandioriva',
                'tempat_lahir' => 'Aceh',
                'tanggal_lahir' => '1998-02-24',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Teuku Umar No.21, Banda Aceh',
                'nomor_telepon' => '081234567875',
                'nama_ibu_kandung' => 'Sandioriva Sari',
            ],
            [
                'nik' => '3501010101010076',
                'email' => 'rama.danendra@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rama Danendra',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1984-05-07',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Solo No.92, Yogyakarta',
                'nomor_telepon' => '081234567876',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010077',
                'email' => 'sari.permata@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sari Permata',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-07-20',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Gubeng No.38, Surabaya',
                'nomor_telepon' => '081234567877',
                'nama_ibu_kandung' => 'Permata Sari',
            ],
            [
                'nik' => '3501010101010078',
                'email' => 'tito.karnavian@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Tito Karnavian',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1981-10-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Thamrin No.115, Jakarta Pusat',
                'nomor_telepon' => '081234567878',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010079',
                'email' => 'umi.latifah@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Umi Latifah',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1994-12-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Riau No.88, Bandung',
                'nomor_telepon' => '081234567879',
                'nama_ibu_kandung' => 'Latifah Sari',
            ],
            [
                'nik' => '3501010101010080',
                'email' => 'vicky.prasetyo@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Vicky Prasetyo',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1986-03-28',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Pandanaran No.97, Semarang',
                'nomor_telepon' => '081234567880',
                'nama_ibu_kandung' => 'Siti Nurjanah',
            ],
            [
                'nik' => '3501010101010081',
                'email' => 'winda.viska@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Winda Viska',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1997-06-10',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sisingamangaraja No.69, Medan',
                'nomor_telepon' => '081234567881',
                'nama_ibu_kandung' => 'Viska Sari',
            ],
            [
                'nik' => '3501010101010082',
                'email' => 'xander.fandy@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Xander Fandy',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1988-08-23',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kemang Raya No.124, Jakarta Selatan',
                'nomor_telepon' => '081234567882',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010083',
                'email' => 'yoga.pratama@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Yoga Pratama',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1982-11-05',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Mataram No.103, Yogyakarta',
                'nomor_telepon' => '081234567883',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3501010101010084',
                'email' => 'zahra.putri@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Zahra Putri',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1995-01-18',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Darmo No.142, Surabaya',
                'nomor_telepon' => '081234567884',
                'nama_ibu_kandung' => 'Putri Sari',
            ],
            [
                'nik' => '3501010101010085',
                'email' => 'ahmad.ripani@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ahmad Ripani',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1987-04-01',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cihampelas No.131, Bandung',
                'nomor_telepon' => '081234567885',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3501010101010086',
                'email' => 'bella.natasha@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Bella Natasha',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1996-06-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kebon Kacang No.72, Jakarta Pusat',
                'nomor_telepon' => '081234567886',
                'nama_ibu_kandung' => 'Natasha Sari',
            ],
            [
                'nik' => '3501010101010087',
                'email' => 'cakra.buwana@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Cakra Buwana',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1989-09-27',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gajah Mada No.113, Semarang',
                'nomor_telepon' => '081234567887',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010088',
                'email' => 'dinda.hawati@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dinda Hawati',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1993-12-10',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Diponegoro No.127, Medan',
                'nomor_telepon' => '081234567888',
                'nama_ibu_kandung' => 'Hawati Sari',
            ],
            [
                'nik' => '3501010101010089',
                'email' => 'eka.wulandari@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Eka Wulandari',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1998-02-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Malioboro No.156, Yogyakarta',
                'nomor_telepon' => '081234567889',
                'nama_ibu_kandung' => 'Wulandari Sari',
            ],
            [
                'nik' => '3501010101010090',
                'email' => 'fajar.setyawan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Fajar Setyawan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1984-05-06',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Raya Gubeng No.168, Surabaya',
                'nomor_telepon' => '081234567890',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010091',
                'email' => 'gita.virgiawan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Gita Virgiawan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-07-19',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Gatot Subroto No.179, Jakarta Selatan',
                'nomor_telepon' => '081234567891',
                'nama_ibu_kandung' => 'Virgiawan Sari',
            ],
            [
                'nik' => '3501010101010092',
                'email' => 'hadi.kurniawan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Hadi Kurniawan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1981-10-01',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Dago No.192, Bandung',
                'nomor_telepon' => '081234567892',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3501010101010093',
                'email' => 'indira.monika@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Indira Monika',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1994-12-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Pandanaran No.203, Semarang',
                'nomor_telepon' => '081234567893',
                'nama_ibu_kandung' => 'Monika Sari',
            ],
            [
                'nik' => '3501010101010094',
                'email' => 'johan.hermawan@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Johan Hermawan',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1986-03-27',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Imam Bonjol No.214, Medan',
                'nomor_telepon' => '081234567894',
                'nama_ibu_kandung' => 'Siti Nurjanah',
            ],
            [
                'nik' => '3501010101010095',
                'email' => 'kartika.dewi@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Kartika Dewi',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1997-06-09',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kebon Sirih No.225, Jakarta Pusat',
                'nomor_telepon' => '081234567895',
                'nama_ibu_kandung' => 'Dewi Sari',
            ],
            [
                'nik' => '3501010101010096',
                'email' => 'lukman.nurhakim@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lukman Nurhakim',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-08-22',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Solo No.236, Yogyakarta',
                'nomor_telepon' => '081234567896',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3501010101010097',
                'email' => 'maya.rasyid@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Maya Rasyid',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1982-11-04',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Raya Darmo No.247, Surabaya',
                'nomor_telepon' => '081234567897',
                'nama_ibu_kandung' => 'Rasyid Sari',
            ],
            [
                'nik' => '3501010101010098',
                'email' => 'nur.hidayat@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nur Hidayat',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1995-01-17',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cipaganti No.258, Bandung',
                'nomor_telepon' => '081234567898',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3501010101010099',
                'email' => 'olivia.zahra@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Olivia Zahra',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1987-03-31',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Thamrin No.269, Jakarta Pusat',
                'nomor_telepon' => '081234567899',
                'nama_ibu_kandung' => 'Zahra Sari',
            ],
            [
                'nik' => '3501010101010100',
                'email' => 'pratama.wicaksono@example.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Pratama Wicaksono',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1996-06-13',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gajah Mada No.280, Semarang',
                'nomor_telepon' => '081234567900',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
        ];

        foreach ($penggunaData as $data) {
            Pengguna::create($data);
        }
    }
}