<?php

namespace Database\Seeders;

use App\Models\Pengguna;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PenggunaSeeder extends Seeder
{
    public function run()
    {
        $penggunaData = [
            [
                'nik' => '3509015401980001',
                'email' => 'budisantoso78@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Budi Santoso',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-05-15',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Mastrip No. 45, Kec. Sumbersari, Jember',
                'nomor_telepon' => '081234567801',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3509022302970002',
                'email' => 'sitinurhayati83@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Siti Nurhayati',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-08-20',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Diponegoro No. 12, Kec. Bondowoso',
                'nomor_telepon' => '082345678902',
                'nama_ibu_kandung' => 'Rohana',
            ],
            [
                'nik' => '3509031203990003',
                'email' => 'atika@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Atika Wardha',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2005-07-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Madura Gg.4, Krajan Mimbaan, Mimbaan, Kec. Panji, Kabupaten Situbondo, Jawa Timur',
                'nomor_telepon' => '082264726499',
                'nama_ibu_kandung' => 'Ibu-Ibu',
            ],
            [
                'nik' => '3509041804000004',
                'email' => 'dewiwulandari67@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dewi Wulandari',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-12-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Dr. Soetomo No. 23, Kec. Banyuwangi',
                'nomor_telepon' => '084567890104',
                'nama_ibu_kandung' => 'Kartini',
            ],
            [
                'nik' => '3509012505010005',
                'email' => 'andifirmansyah79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Andi Firmansyah',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-01-25',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kalimantan No. 56, Kec. Kaliwates, Jember',
                'nomor_telepon' => '085678901205',
                'nama_ibu_kandung' => 'Rukmini',
            ],
            [
                'nik' => '3509020606020006',
                'email' => 'linaanggraini84@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lina Anggraini',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-06-06',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. A. Yani No. 34, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '086789012306',
                'nama_ibu_kandung' => 'Rohana',
            ],
            [
                'nik' => '3509033007030007',
                'email' => 'rizkymaulana92@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rizky Maulana',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-07-30',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jend. Sudirman No. 89, Kec. Situbondo',
                'nomor_telepon' => '087890123407',
                'nama_ibu_kandung' => 'Mardiana',
            ],
            [
                'nik' => '3509041408040008',
                'email' => 'ayuwulandari73@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ayu Wulandari',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-08-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Panglima Sudirman No. 15, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '088901234508',
                'nama_ibu_kandung' => 'Sari Dewi',
            ],
            [
                'nik' => '3509010909050009',
                'email' => 'herisusanto85@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Heri Susanto',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-09-09',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gajah Mada No. 67, Kec. Patrang, Jember',
                'nomor_telepon' => '089012345609',
                'nama_ibu_kandung' => 'Sulastri',
            ],
            [
                'nik' => '3509022710060010',
                'email' => 'fitrihandayani88@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Fitri Handayani',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-10-27',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Merdeka No. 42, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '081112345610',
                'nama_ibu_kandung' => 'Yuliani',
            ],
            [
                'nik' => '3509031511070011',
                'email' => 'jokowidodo94@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Joko Widodo',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-11-15',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Raya Panji No. 31, Kec. Panji, Situbondo',
                'nomor_telepon' => '082223456711',
                'nama_ibu_kandung' => 'Sudjiatmi',
            ],
            [
                'nik' => '3509040602080012',
                'email' => 'srimulyani76@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sri Mulyani',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-02-06',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Veteran No. 28, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '083334567812',
                'nama_ibu_kandung' => 'Retno Samudro',
            ],
            [
                'nik' => '3509012203090013',
                'email' => 'ahmaddahlan89@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ahmad Dahlan',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-03-22',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jawa No. 53, Kec. Sumbersari, Jember',
                'nomor_telepon' => '084445678913',
                'nama_ibu_kandung' => 'Siti Walidah',
            ],
            [
                'nik' => '3509021804100014',
                'email' => 'ratnasari81@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ratna Sari',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-04-18',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Pahlawan No. 19, Kec. Bondowoso',
                'nomor_telepon' => '085556789014',
                'nama_ibu_kandung' => 'Dewi Kusuma',
            ],
            [
                'nik' => '3509030905110015',
                'email' => 'bambangpamungkas95@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Bambang Pamungkas',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-05-09',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kenanga No. 74, Kec. Mangaran, Situbondo',
                'nomor_telepon' => '086667890115',
                'nama_ibu_kandung' => 'Siti Maryam',
            ],
            [
                'nik' => '3509042912120016',
                'email' => 'diansastro72@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dian Sastrowardoyo',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-12-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Gatot Subroto No. 36, Kec. Banyuwangi',
                'nomor_telepon' => '087778901216',
                'nama_ibu_kandung' => 'Sri Hastuti',
            ],
            [
                'nik' => '3509011701130017',
                'email' => 'iwanfals86@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Iwan Fals',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-01-17',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Sumatra No. 61, Kec. Kaliwates, Jember',
                'nomor_telepon' => '088889012317',
                'nama_ibu_kandung' => 'Yati',
            ],
            [
                'nik' => '3509020802140018',
                'email' => 'agnesmonica77@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Agnes Monica',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-02-08',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Flores No. 27, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '089990123418',
                'nama_ibu_kandung' => 'Jenny Siswono',
            ],
            [
                'nik' => '3509032503150019',
                'email' => 'susipudjiastuti93@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Susi Pudjiastuti',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-03-25',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Mawar No. 48, Kec. Situbondo',
                'nomor_telepon' => '081101234519',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509041404160020',
                'email' => 'aniesbaswedan90@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Anies Baswedan',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-04-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kh. Wahid Hasyim No. 22, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '082212345620',
                'nama_ibu_kandung' => 'Aliyah Rasyid',
            ],
            [
                'nik' => '3509010505170021',
                'email' => 'riniindrawati87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rini Indrawati',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Bali No. 39, Kec. Sumbersari, Jember',
                'nomor_telepon' => '083323456721',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3509022606180022',
                'email' => 'ridwankamil96@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ridwan Kamil',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Cendana No. 55, Kec. Bondowoso',
                'nomor_telepon' => '084434567822',
                'nama_ibu_kandung' => 'Tuti Alawiyah',
            ],
            [
                'nik' => '3509031707190023',
                'email' => 'diananurjanah82@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Diana Nurjanah',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-07-17',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Melati No. 63, Kec. Panarukan, Situbondo',
                'nomor_telepon' => '085545678923',
                'nama_ibu_kandung' => 'Siti Komariah',
            ],
            [
                'nik' => '3509040808200024',
                'email' => 'tommyprayitno91@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Tommy Prayitno',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-08-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Anggrek No. 17, Kec. Banyuwangi',
                'nomor_telepon' => '086656789024',
                'nama_ibu_kandung' => 'Siti Hartinah',
            ],
            [
                'nik' => '3509012912210025',
                'email' => 'megachandra75@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Mega Chandra',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-12-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Nusantara No. 71, Kec. Patrang, Jember',
                'nomor_telepon' => '087767890125',
                'nama_ibu_kandung' => 'Sukmawati',
            ],
            [
                'nik' => '3509022003220026',
                'email' => 'jokosiswanto89@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Joko Siswanto',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-03-20',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Surya No. 44, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '088878901226',
                'nama_ibu_kandung' => 'Sudjiatmi',
            ],
            [
                'nik' => '3509031111230027',
                'email' => 'srirahayu83@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sri Rahayu',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-11-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kenari No. 52, Kec. Situbondo',
                'nomor_telepon' => '089989012327',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509040202240028',
                'email' => 'budigunawan94@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Budi Gunawan',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-02-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Merpati No. 33, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '081109012428',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3509012303250029',
                'email' => 'saridewi78@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sari Dewi',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-03-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Rajawali No. 26, Kec. Kaliwates, Jember',
                'nomor_telepon' => '082210123529',
                'nama_ibu_kandung' => 'Dewi Lestari',
            ],
            [
                'nik' => '3509021404260030',
                'email' => 'agusharimurti87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Agus Harimurti',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-04-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Elang No. 58, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '083321234630',
                'nama_ibu_kandung' => 'Siti Nurhaliza',
            ],
            [
                'nik' => '3509030505270031',
                'email' => 'intanjuwita85@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Intan Juwita',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Cempaka No. 41, Kec. Panji, Situbondo',
                'nomor_telepon' => '084432345731',
                'nama_ibu_kandung' => 'Rosmalia',
            ],
            [
                'nik' => '3509042606280032',
                'email' => 'donianton92@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Doni Anton',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Flamboyan No. 29, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '085543456832',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509011707290033',
                'email' => 'linamarlina79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lina Marlina',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-07-17',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Teratai No. 35, Kec. Sumbersari, Jember',
                'nomor_telepon' => '086654567933',
                'nama_ibu_kandung' => 'Marlina',
            ],
            [
                'nik' => '3509020808300034',
                'email' => 'rezarahadian88@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Reza Rahadian',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-08-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kamboja No. 47, Kec. Bondowoso',
                'nomor_telepon' => '087765679034',
                'nama_ibu_kandung' => 'Dewi Rahayu',
            ],
            [
                'nik' => '3509032909310035',
                'email' => 'ninatamam81@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nina Tamam',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-09-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sakura No. 59, Kec. Mangaran, Situbondo',
                'nomor_telepon' => '088876780135',
                'nama_ibu_kandung' => 'Siti Fatimah',
            ],
            [
                'nik' => '3509042010320036',
                'email' => 'arifinilham93@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Arifin Ilham',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-10-20',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Tulip No. 24, Kec. Banyuwangi',
                'nomor_telepon' => '089987891236',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509011111330037',
                'email' => 'dellaanggraini86@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Della Anggraini',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-11-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Alamanda No. 68, Kec. Patrang, Jember',
                'nomor_telepon' => '081198902337',
                'nama_ibu_kandung' => 'Rina Anggraini',
            ],
            [
                'nik' => '3509020212340038',
                'email' => 'firmanadi90@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Firman Adi',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-12-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Bougenville No. 37, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '082209013438',
                'nama_ibu_kandung' => 'Siti Rohana',
            ],
            [
                'nik' => '3509032313350039',
                'email' => 'gitagutawa84@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Gita Gutawa',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-01-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kaktus No. 51, Kec. Situbondo',
                'nomor_telepon' => '083310124539',
                'nama_ibu_kandung' => 'Siti Nurjanah',
            ],
            [
                'nik' => '3509041414360040',
                'email' => 'hadiprayitno95@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Hadi Prayitno',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Lavender No. 32, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '084421235640',
                'nama_ibu_kandung' => 'Siti Komariah',
            ],
            [
                'nik' => '3509010505370041',
                'email' => 'indahkusuma82@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Indah Kusuma',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Manggis No. 43, Kec. Sumbersari, Jember',
                'nomor_telepon' => '085532346741',
                'nama_ibu_kandung' => 'Dewi Kusuma',
            ],
            [
                'nik' => '3509022606380042',
                'email' => 'jajamihardja89@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Jaja Mihardja',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Durian No. 54, Kec. Bondowoso',
                'nomor_telepon' => '086643457842',
                'nama_ibu_kandung' => 'Siti Maryam',
            ],
            [
                'nik' => '3509031707390043',
                'email' => 'kartikasari77@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Kartika Sari',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-07-17',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Rambutan No. 62, Kec. Panarukan, Situbondo',
                'nomor_telepon' => '087754568943',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3509040808400044',
                'email' => 'lukmanhakim91@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lukman Hakim',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-08-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Mangga No. 16, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '088865679044',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3509012912410045',
                'email' => 'mayaseptiani86@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Maya Septiani',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-12-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Jeruk No. 70, Kec. Kaliwates, Jember',
                'nomor_telepon' => '089976780145',
                'nama_ibu_kandung' => 'Septi Wulandari',
            ],
            [
                'nik' => '3509022003420046',
                'email' => 'nurdinhalid93@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nurdin Halid',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-03-20',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Apel No. 45, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '081187891246',
                'nama_ibu_kandung' => 'Siti Komariah',
            ],
            [
                'nik' => '3509031111430047',
                'email' => 'oktaviani79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Okta Viani',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-11-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Pisang No. 53, Kec. Situbondo',
                'nomor_telepon' => '082298902347',
                'nama_ibu_kandung' => 'Viani Sari',
            ],
            [
                'nik' => '3509040202440048',
                'email' => 'pratimaputra87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Pratima Putra',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-02-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Salak No. 34, Kec. Banyuwangi',
                'nomor_telepon' => '083309013448',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509012303450049',
                'email' => 'queenmiranda84@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Queen Miranda',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-03-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Semangka No. 27, Kec. Patrang, Jember',
                'nomor_telepon' => '084310124549',
                'nama_ibu_kandung' => 'Miranda Sari',
            ],
            [
                'nik' => '3509021404460050',
                'email' => 'rizalramli92@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rizal Ramli',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-04-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Melon No. 57, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '085421235650',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509030505470051',
                'email' => 'salsabila88@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Salsa Bila',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Anggur No. 42, Kec. Panji, Situbondo',
                'nomor_telepon' => '086532346751',
                'nama_ibu_kandung' => 'Bila Sari',
            ],
            [
                'nik' => '3509042606480052',
                'email' => 'taufikhidayat85@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Taufik Hidayat',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Nanas No. 30, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '087643457852',
                'nama_ibu_kandung' => 'Siti Nurhayati',
            ],
            [
                'nik' => '3509011707490053',
                'email' => 'umipurnama81@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Umi Purnama',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-07-17',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Alpukat No. 36, Kec. Sumbersari, Jember',
                'nomor_telepon' => '088754568953',
                'nama_ibu_kandung' => 'Purnama Sari',
            ],
            [
                'nik' => '3509020808500054',
                'email' => 'vinobastian90@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Vino Bastian',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-08-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jambu No. 48, Kec. Bondowoso',
                'nomor_telepon' => '089865679054',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509032909510055',
                'email' => 'wulanguritno79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Wulan Guritno',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-09-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kedondong No. 60, Kec. Mangaran, Situbondo',
                'nomor_telepon' => '081176780155',
                'nama_ibu_kandung' => 'Guritno Sari',
            ],
            [
                'nik' => '3509042010520056',
                'email' => 'xavierheru93@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Xavier Heru',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-10-20',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Belimbing No. 25, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '082287891256',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509011111530057',
                'email' => 'yunisari86@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Yuni Sari',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-11-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Duku No. 69, Kec. Kaliwates, Jember',
                'nomor_telepon' => '083398902357',
                'nama_ibu_kandung' => 'Sari Indah',
            ],
            [
                'nik' => '3509020212640058',
                'email' => 'zainudinamin89@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Zainudin Amin',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-12-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Langsat No. 38, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '084409013458',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3509032313750059',
                'email' => 'aininurjanah82@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Aini Nurjanah',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-01-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sukun No. 52, Kec. Situbondo',
                'nomor_telepon' => '085510124559',
                'nama_ibu_kandung' => 'Nurjanah Sari',
            ],
            [
                'nik' => '3509041414860060',
                'email' => 'bambangsusilo95@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Bambang Susilo',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Nangka No. 33, Kec. Banyuwangi',
                'nomor_telepon' => '086621235660',
                'nama_ibu_kandung' => 'Susilo Wati',
            ],
            [
                'nik' => '3509010505970061',
                'email' => 'cindygracia87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Cindy Gracia',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sawo No. 44, Kec. Patrang, Jember',
                'nomor_telepon' => '087732346761',
                'nama_ibu_kandung' => 'Gracia Sari',
            ],
            [
                'nik' => '3509022606980062',
                'email' => 'dodimizwar91@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dodi Mizwar',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Sirsak No. 55, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '088843457862',
                'nama_ibu_kandung' => 'Siti Maryam',
            ],
            [
                'nik' => '3509031707990063',
                'email' => 'ekagustiwana84@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Eka Gustiwana',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-07-17',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Leci No. 63, Kec. Panarukan, Situbondo',
                'nomor_telepon' => '089954568963',
                'nama_ibu_kandung' => 'Gustiwana Sari',
            ],
            [
                'nik' => '3509040808000064',
                'email' => 'firatitania78@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Fira Titania',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-08-08',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Delima No. 17, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '081165679064',
                'nama_ibu_kandung' => 'Titania Sari',
            ],
            [
                'nik' => '3509012912010065',
                'email' => 'gilangramadhan92@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Gilang Ramadhan',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-12-29',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jambu Air No. 72, Kec. Sumbersari, Jember',
                'nomor_telepon' => '082276780165',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509022003020066',
                'email' => 'hannysaputri86@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Hanny Saputri',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-03-20',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kweni No. 46, Kec. Bondowoso',
                'nomor_telepon' => '083387891266',
                'nama_ibu_kandung' => 'Saputri Wati',
            ],
            [
                'nik' => '3509031111030067',
                'email' => 'irsyadilham89@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Irsyad Ilham',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-11-11',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gandaria No. 54, Kec. Situbondo',
                'nomor_telepon' => '084498902367',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509040202040068',
                'email' => 'jessicamila83@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Jessica Mila',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-02-02',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Matoa No. 35, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '085509013468',
                'nama_ibu_kandung' => 'Mila Sari',
            ],
            [
                'nik' => '3509012303050069',
                'email' => 'kurniawandewa87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Kurniawan Dewa',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-03-23',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kepel No. 28, Kec. Kaliwates, Jember',
                'nomor_telepon' => '086610124569',
                'nama_ibu_kandung' => 'Siti Nurhayati',
            ],
            [
                'nik' => '3509021404060070',
                'email' => 'lailachoiriah81@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Laila Choiriah',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-04-14',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Cermai No. 59, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '087721235670',
                'nama_ibu_kandung' => 'Choiriah Sari',
            ],
            [
                'nik' => '3509030505070071',
                'email' => 'muhammadali94@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Muhammad Ali',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-05-05',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Bisbul No. 43, Kec. Panji, Situbondo',
                'nomor_telepon' => '088832346771',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3509042606080072',
                'email' => 'nadiaputri88@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nadia Putri',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-06-26',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kesemek No. 31, Kec. Banyuwangi',
                'nomor_telepon' => '089943457872',
                'nama_ibu_kandung' => 'Putri Sari',
            ],
            [
                'nik' => '3509011707090073',
                'email' => 'oscarlawalata85@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Oscar Lawalata',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-07-17',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Lobi No. 37, Kec. Patrang, Jember',
                'nomor_telepon' => '081154568973',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3509020808100074',
                'email' => 'putritanjung79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Putri Tanjung',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-08-08',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Canistel No. 49, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '082265679074',
                'nama_ibu_kandung' => 'Tanjung Sari',
            ],
            [
                'nik' => '3509032909110075',
                'email' => 'qorysandioriva93@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Qory Sandioriva',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-09-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Babako No. 61, Kec. Mangaran, Situbondo',
                'nomor_telepon' => '083376780175',
                'nama_ibu_kandung' => 'Sandioriva Sari',
            ],
            [
                'nik' => '3509042010120076',
                'email' => 'ramadanendra87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Rama Danendra',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-10-20',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Carica No. 26, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '084487891276',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509011111130077',
                'email' => 'saripermata82@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Sari Permata',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-11-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Gowok No. 70, Kec. Sumbersari, Jember',
                'nomor_telepon' => '085598902377',
                'nama_ibu_kandung' => 'Permata Sari',
            ],
            [
                'nik' => '3509020212240078',
                'email' => 'titokarnavian90@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Tito Karnavian',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-12-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kecapi No. 39, Kec. Bondowoso',
                'nomor_telepon' => '086609013478',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509032313350079',
                'email' => 'umilatifah84@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Umi Latifah',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-01-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Menteng No. 53, Kec. Situbondo',
                'nomor_telepon' => '087710124579',
                'nama_ibu_kandung' => 'Latifah Sari',
            ],
            [
                'nik' => '3509041414460080',
                'email' => 'vickyprasetyo95@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Vicky Prasetyo',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Namnam No. 34, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '088821235680',
                'nama_ibu_kandung' => 'Siti Nurjanah',
            ],
            [
                'nik' => '3509010505570081',
                'email' => 'windaviska88@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Winda Viska',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Buni No. 45, Kec. Kaliwates, Jember',
                'nomor_telepon' => '089932346781',
                'nama_ibu_kandung' => 'Viska Sari',
            ],
            [
                'nik' => '3509022606680082',
                'email' => 'xanderfandy91@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Xander Fandy',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Gnetum No. 56, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '081143457882',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509031707790083',
                'email' => 'yogapratama85@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Yoga Pratama',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-07-17',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Jamblang No. 64, Kec. Panji, Situbondo',
                'nomor_telepon' => '082254568983',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3509040808800084',
                'email' => 'zahraputri79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Zahra Putri',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-08-08',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Kawista No. 18, Kec. Banyuwangi',
                'nomor_telepon' => '083365679084',
                'nama_ibu_kandung' => 'Putri Sari',
            ],
            [
                'nik' => '3509012912910085',
                'email' => 'ahmadripani92@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Ahmad Ripani',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-12-29',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Lontar No. 73, Kec. Patrang, Jember',
                'nomor_telepon' => '084476780185',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
            [
                'nik' => '3509022003020086',
                'email' => 'bellanatasha86@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Bella Natasha',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-03-20',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Mundu No. 47, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '085587891286',
                'nama_ibu_kandung' => 'Natasha Sari',
            ],
            [
                'nik' => '3509031111130087',
                'email' => 'cakrabuwana89@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Cakra Buwana',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-11-11',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Rukem No. 55, Kec. Situbondo',
                'nomor_telepon' => '086698902387',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509040202240088',
                'email' => 'dindahawati83@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Dinda Hawati',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-02-02',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sawo Kecik No. 36, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '087709013488',
                'nama_ibu_kandung' => 'Hawati Sari',
            ],
            [
                'nik' => '3509012303350089',
                'email' => 'ekawulandari87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Eka Wulandari',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-03-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Tanjung No. 29, Kec. Sumbersari, Jember',
                'nomor_telepon' => '088810124589',
                'nama_ibu_kandung' => 'Wulandari Sari',
            ],
            [
                'nik' => '3509021404460090',
                'email' => 'fajarsetyawan81@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Fajar Setyawan',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-04-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Pacar No. 60, Kec. Bondowoso',
                'nomor_telepon' => '089921235690',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509030505570091',
                'email' => 'gitavirgiawan94@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Gita Virgiawan',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-05-05',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sala No. 44, Kec. Panarukan, Situbondo',
                'nomor_telepon' => '081132346791',
                'nama_ibu_kandung' => 'Virgiawan Sari',
            ],
            [
                'nik' => '3509042606680092',
                'email' => 'hadikurniawan88@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Hadi Kurniawan',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-06-26',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Bungur No. 32, Kec. Genteng, Banyuwangi',
                'nomor_telepon' => '082243457892',
                'nama_ibu_kandung' => 'Siti Rahma',
            ],
            [
                'nik' => '3509011707790093',
                'email' => 'indiramonika85@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Indira Monika',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2004-07-17',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Asam No. 38, Kec. Kaliwates, Jember',
                'nomor_telepon' => '083354568993',
                'nama_ibu_kandung' => 'Monika Sari',
            ],
            [
                'nik' => '3509020808800094',
                'email' => 'johanhermawan79@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Johan Hermawan',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2005-08-08',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Kranji No. 50, Kec. Prajekan, Bondowoso',
                'nomor_telepon' => '084465679094',
                'nama_ibu_kandung' => 'Siti Nurjanah',
            ],
            [
                'nik' => '3509032909910095',
                'email' => 'kartikadewi93@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Kartika Dewi',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2006-09-29',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Johar No. 62, Kec. Situbondo',
                'nomor_telepon' => '085576780195',
                'nama_ibu_kandung' => 'Dewi Sari',
            ],
            [
                'nik' => '3509042010020096',
                'email' => 'lukmannurhakim87@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Lukman Nurhakim',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2007-10-20',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Trembesi No. 27, Kec. Banyuwangi',
                'nomor_telepon' => '086687891296',
                'nama_ibu_kandung' => 'Siti Aisyah',
            ],
            [
                'nik' => '3509011111130097',
                'email' => 'mayarasyid82@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Maya Rasyid',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '2000-11-11',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Angsana No. 71, Kec. Patrang, Jember',
                'nomor_telepon' => '087798902397',
                'nama_ibu_kandung' => 'Rasyid Sari',
            ],
            [
                'nik' => '3509020212240098',
                'email' => 'nurhidayat90@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Nur Hidayat',
                'tempat_lahir' => 'Bondowoso',
                'tanggal_lahir' => '2001-12-02',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Mahoni No. 40, Kec. Tamanan, Bondowoso',
                'nomor_telepon' => '088809013498',
                'nama_ibu_kandung' => 'Siti Rahayu',
            ],
            [
                'nik' => '3509032313350099',
                'email' => 'oliviazahra84@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Olivia Zahra',
                'tempat_lahir' => 'Situbondo',
                'tanggal_lahir' => '2002-01-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat_lengkap' => 'Jl. Sonokeling No. 54, Kec. Mangaran, Situbondo',
                'nomor_telepon' => '089910124599',
                'nama_ibu_kandung' => 'Zahra Sari',
            ],
            [
                'nik' => '3509041414460100',
                'email' => 'pratmawicaksono95@gmail.com',
                'password' => bcrypt('password'),
                'nama_lengkap' => 'Pratma Wicaksono',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2003-02-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat_lengkap' => 'Jl. Beringin No. 35, Kec. Rogojampi, Banyuwangi',
                'nomor_telepon' => '081121235600',
                'nama_ibu_kandung' => 'Siti Aminah',
            ],
        ];

        foreach ($penggunaData as $data) {
            Pengguna::create($data);
        }
    }
}